apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: 'nginx'
  name: 'nginx-default-backend'
spec:
  externalIPs: []
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: 'nginx'
    component: 'default-backend'
  type: 'ClusterIP'
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: 'nginx'
  name: 'default-backend'
spec:
  replicas: 1
  template:
    metadata:
      annotations: {}
      labels:
        app: 'nginx'
    spec:
      containers:
        - name: 'nginx-default-backend'
          image: "gcr.io/google_containers/defaultbackend:1.3"
          imagePullPolicy: "IfNotPresent"
          args: []
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi
      nodeSelector: {}
      tolerations: []
      terminationGracePeriodSeconds: 60
