apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  labels:
    app: 'grafana'
    component: 'grafana'
  name: 'grafana'
spec:
  accessModes:
    - 'ReadWriteOnce'
  storageClassName: 'nfs-slow'
  resources:
    requests:
      storage: '1Gi'
