apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 'prometheus-server'
  labels:
    app: 'prometheus'
    component: 'server'
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: 'nfs-slow'
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "prometheus-alertmanager"
  labels:
    app: "prometheus"
    component: "alertmanager"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: 'nfs-slow'
  resources:
    requests:
      storage: 2Gi
