apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: 'nginx-lego'
  name: 'nginx-lego'
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: 'nginx-lego'
  name: 'nginx-lego'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: 'nginx-lego'
    spec:
      serviceAccountName: 'nginx-lego'
      containers:
        - name: 'nginx-lego'
          image: 'jetstack/kube-lego:0.1.4'
          imagePullPolicy: 'IfNotPresent'
          env:
            - name: LEGO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LEGO_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: LEGO_EMAIL
              value: 'acmcarther@gmail.com'
            - name: LEGO_URL
              value: 'https://acme-v01.api.letsencrypt.org/directory'
            - name: LEGO_LOG_LEVEL
              value: verbose
            - name: LEGO_SUPPORTED_INGRESS_CLASS
              value: nginx
            - name: LEGO_DEFAULT_INGRESS_CLASS
              value: nginx
          resources: {}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8080
