apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: 'openvpn'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: 'openvpn'
        type: openvpn
    spec:
      containers:
      - name: 'openvpn'
        image: 'jfelten/openvpn-docker'
        imagePullPolicy: 'IfNotPresent'
        command: ["/etc/openvpn/setup/configure.sh"]
        ports:
        - containerPort: 443
          name: openvpn
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        resources:
          requests:
            cpu: 300m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 128Mi
        volumeMounts:
          - mountPath: /etc/openvpn/setup
            name: openvpn
            readOnly: false
          - mountPath: /etc/openvpn/certs
            name: certs
            readOnly: false
      volumes:
      - name: openvpn
        configMap:
          name: 'openvpn'
          defaultMode: 0775
      - name: certs
        persistentVolumeClaim:
          claimName: 'openvpn'
---
kind: Service
apiVersion: v1
metadata:
  name: 'openvpn'
  labels:
    type: openvpn
spec:
  ports:
    - name: openvpn
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: 'openvpn'
  type: 'ClusterIP'
