apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: 'prometheus'
    component: 'kubestatemetrics'
  name: 'prometheus-kubestatemetrics'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: 'prometheus'
        component: 'kubestatemetrics'
    spec:
      serviceAccountName: 'prometheus-kubestatemetrics'
      containers:
        - name: 'prometheus-kubestatemetrics'
          image: "gcr.io/google_containers/kube-state-metrics:v1.1.0-rc.0"
          imagePullPolicy: 'IfNotPresent'
          ports:
            - name: metrics
              containerPort: 8080
          resources: {}
      nodeSelector: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: 'prometheus'
    component: 'kubestatemetrics'
  name: 'prometheus-kubestatemetrics'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: 'prometheus'
    component: 'kubestatemetrics'
  name: 'prometheus-kubestatemetrics'
spec:
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: 'prometheus'
    component: 'kubestatemetrics'
  type: 'ClusterIP'
